# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec
# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: leapp-repository
downstream_package_name: leapp-repository
upstream_tag_template: 'v{version}'
merge_pr_in_ci: false

srpm_build_deps:
- make

# This is just for the build from the CLI - all other builds for jobs use own
# actions
actions:
  create-archive:
  - bash -c "rm -f packaging/deps-pkgs.tar.gz"
  - bash -c "make source"
  - bash -c "mv packaging/sources/*.gz packaging/"
  - bash -c "find packaging/*.gz -type f"
  fix-spec-file:
  - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
  post-upstream-clone:
  # builds from PRs should have lower NVR than those from main branch
  - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from PRs should have lower NVR than those from main branch
    - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: commit
  metadata:
    branch: main
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from main branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: release
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from main branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"


# NOTE: to see what envars, targets, .. can be set in tests, see
# the configuration of tests here:
#  7toX path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/rhel7/config.yaml
# >7tox path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/main/config.yaml
# Available only to RH Employees.

# ###################################################################### #
# ############################## 8 TO 9 ################################ #
# ###################################################################### #

# ###################################################################### #
# ### Abstract job definitions to make individual tests/jobs smaller ### #
# ###################################################################### #

#NOTE(pstodulk) putting default values in abstract jobs as from 8.10, as this
# is the last RHEL 8 release and all new future tests will start from this
# one release.

# This job is never triggered - we define abstract anchor that are reused in jobs that 'inherit'
# and have actionable triggers
- &sanity-abstract-8to9
  job: tests
  trigger: ignore
  fmf_url: "https://gitlab.cee.redhat.com/oamg/leapp-tests"
  fmf_ref: "main"
  use_internal_tf: True
  labels:
    - sanity
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: sanity-abstract-8to9
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9'
    environments:
      - &tmt-env-settings-810to94
        tmt:
          context: &tmt-context-810to94
            distro: "rhel-8.10"
            distro_target: "rhel-9.4"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-810to96
        tmt:
          context: &tmt-context-810to96
            distro: "rhel-8.10"
            distro_target: "rhel-9.6"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-810to97
        tmt:
          context: &tmt-context-810to97
            distro: "rhel-8.10"
            distro_target: "rhel-9.7"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-810to98
        tmt:
          context: &tmt-context-810to98
            distro: "rhel-8.10"
            distro_target: "rhel-9.8"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test

- &sanity-abstract-8to9-aws
  <<: *sanity-abstract-8to9
  labels:
    - sanity
    - aws
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10-rhui]
  identifier: sanity-abstract-8to9-aws

- &beaker-minimal-8to9-abstract-ondemand
  <<: *sanity-abstract-8to9
  manual_trigger: True
  labels:
    - beaker-minimal
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: beaker-minimal-8to9-abstract-ondemand

- &kernel-rt-abstract-8to9-ondemand
  <<: *beaker-minimal-8to9-abstract-ondemand
  labels:
    - kernel-rt
  identifier: sanity-8to9-kernel-rt-abstract-ondemand

# ###################################################################### #
# ######################### Individual tests ########################### #
# ###################################################################### #

# ###################################################################### #
# ############################# 8.10 > 9.4 ############################# #
# ###################################################################### #

- &sanity-810to94
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.4
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to94
  env: &env-810to94
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.4"
    LEAPP_TARGET_PRODUCT_CHANNEL: "EUS"

# On-demand minimal beaker tests
- &beaker-minimal-810to94
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to94
  env:
    <<: *env-810to94

# On-demand kernel-rt tests
- &kernel-rt-810to94
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true & tag:-rhsm'
    environments:
      - tmt:
          context: *tmt-context-810to94
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    <<: *env-810to94


# ###################################################################### #
# ############################# 8.10 > 9.6 ############################# #
# ###################################################################### #

- &sanity-810to96
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.6
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to96
  env: &env-810to96
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.6"

# On-demand minimal beaker tests
- &beaker-minimal-810to96
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to96
  env:
    <<: *env-810to96

# On-demand kernel-rt tests
- &kernel-rt-810to96
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to96
  env:
    <<: *env-810to96

- &sanity-810to96-aws
  <<: *sanity-abstract-8to9-aws
  trigger: pull_request
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10-rhui]
  identifier: sanity-8.10to9.6-aws
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:rhui-aws-tier0 & enabled:true & tag:-rhsm'
    environments:
      - tmt:
          context: *tmt-context-810to96
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    <<: *env-810to96


# ###################################################################### #
# ############################# 8.10 > 9.7 ############################# #
# ###################################################################### #

- &sanity-810to97
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.7
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to97
  env: &env-810to97
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.7"

# On-demand minimal beaker tests
- &beaker-minimal-810to97
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.7
    - 8.10to9.7
  identifier: sanity-8.10to9.7-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to97
  env:
    <<: *env-810to97

# On-demand kernel-rt tests
- &kernel-rt-810to97
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.7
    - 8.10to9.7
  identifier: sanity-8.10to9.7-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-810to97
  env:
    <<: *env-810to97

# ###################################################################### #
# ############################## 9 TO 10 ################################ #
# ###################################################################### #

# ###################################################################### #
# ### Abstract job definitions to make individual tests/jobs smaller ### #
# ###################################################################### #

- &sanity-abstract-9to10
  job: tests
  trigger: ignore
  fmf_url: "https://gitlab.cee.redhat.com/oamg/leapp-tests"
  fmf_ref: "main"
  use_internal_tf: True
  labels:
    - sanity
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6.0-Nightly]
  identifier: sanity-abstract-9to10
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:9to10'
    environments:
      - &tmt-env-settings-96to100
        tmt:
          context: &tmt-context-96to100
            distro: "rhel-9.6"
            distro_target: "rhel-10.0"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-97to101
        tmt:
          context: &tmt-context-97to101
            distro: "rhel-9.7"
            distro_target: "rhel-10.1"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-98to102
        tmt:
          context: &tmt-context-98to102
            distro: "rhel-9.8"
            distro_target: "rhel-10.2"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test

- &sanity-abstract-9to10-aws
  <<: *sanity-abstract-9to10
  labels:
    - sanity
    - aws
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6-rhui]
  identifier: sanity-abstract-9to10-aws

- &beaker-minimal-9to10-abstract-ondemand
  <<: *sanity-abstract-9to10
  manual_trigger: True
  labels:
    - beaker-minimal
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6.0-Nightly]
  identifier: beaker-minimal-9to10-abstract-ondemand

- &kernel-rt-abstract-9to10-ondemand
  <<: *beaker-minimal-9to10-abstract-ondemand
  labels:
    - kernel-rt
  identifier: sanity-9to10-kernel-rt-abstract-ondemand

# ###################################################################### #
# ######################### Individual tests ########################### #
# ###################################################################### #

# ###################################################################### #
# ############################# 9.6 > 10.0 ############################# #
# ###################################################################### #

- &sanity-96to100
  <<: *sanity-abstract-9to10
  trigger: pull_request
  identifier: sanity-9.6to10.0
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6.0-Nightly]
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:9to10 & tag:tier0 & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-96to100
  env: &env-96to100
    SOURCE_RELEASE: "9.6"
    TARGET_RELEASE: "10.0"

# On-demand minimal beaker tests
- &beaker-minimal-96to100
  <<: *beaker-minimal-9to10-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-9.6to10.0
    - 9.6to10.0
  identifier: sanity-9.6to10.0-beaker-minimal-ondemand
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6-Nightly]
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-96to100
  env:
    <<: *env-96to100

# On-demand kernel-rt tests
- &kernel-rt-96to100
  <<: *kernel-rt-abstract-9to10-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-9.6to10.0
    - 9.6to10.0
  identifier: sanity-9.6to10.0-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-96to100
  env:
    <<: *env-96to100

# ###################################################################### #
# ############################# 9.7 > 10.1 ############################# #
# ###################################################################### #

- &sanity-97to101
  <<: *sanity-abstract-9to10
  trigger: pull_request
  identifier: sanity-9.7to10.1
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.7.0-Nightly]
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:9to10 & tag:tier0 & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-97to101
  env: &env-97to101
    SOURCE_RELEASE: "9.7"
    TARGET_RELEASE: "10.1"

# On-demand minimal beaker tests
- &beaker-minimal-97to101
  <<: *beaker-minimal-9to10-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-9.7to10.1
    - 9.7to10.1
  identifier: sanity-9.7to10.1-beaker-minimal-ondemand
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.7-Nightly]
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-97to101
  env:
    <<: *env-97to101

# On-demand kernel-rt tests
- &kernel-rt-97to101
  <<: *kernel-rt-abstract-9to10-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-9.7to10.1
    - 9.7to10.1
  identifier: sanity-9.7to10.1-kernel-rt-ondemand
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.7-Nightly]
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true & tag:-rhsm'
    environments:
      - *tmt-env-settings-97to101
  env:
    <<: *env-97to101
