# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec
# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: leapp-repository
downstream_package_name: leapp-repository
upstream_tag_template: 'v{version}'
merge_pr_in_ci: false

# This is just for the build from the CLI - all other builds for jobs use own
# actions
actions:
  create-archive:
  - bash -c "rm -f packaging/deps-pkgs.tar.gz"
  - bash -c "make source"
  - bash -c "mv packaging/sources/*.gz packaging/"
  - bash -c "find packaging/*.gz -type f"
  fix-spec-file:
  - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
  post-upstream-clone:
  # builds from PRs should have lower NVR than those from master branch
  - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-7-x86_64
    - epel-8-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from PRs should have lower NVR than those from master branch
    - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: commit
  metadata:
    branch: master
    owner: "@oamg"
    project: leapp
    targets:
    - epel-7-x86_64
    - epel-8-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from master branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: release
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-7-x86_64
    - epel-8-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from master branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"
