# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec
# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: leapp-repository
downstream_package_name: leapp-repository
upstream_tag_template: 'v{version}'
merge_pr_in_ci: false

srpm_build_deps:
- make

# This is just for the build from the CLI - all other builds for jobs use own
# actions
actions:
  create-archive:
  - bash -c "rm -f packaging/deps-pkgs.tar.gz"
  - bash -c "make source"
  - bash -c "mv packaging/sources/*.gz packaging/"
  - bash -c "find packaging/*.gz -type f"
  fix-spec-file:
  - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
  post-upstream-clone:
  # builds from PRs should have lower NVR than those from main branch
  - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from PRs should have lower NVR than those from main branch
    - bash -c "sed -i \"s/1%{?dist}/0%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: commit
  metadata:
    branch: main
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from main branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"
- job: copr_build
  trigger: release
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
  actions:
    create-archive:
    - bash -c "rm -f packaging/deps-pkgs.tar.gz"
    - bash -c "make source"
    - bash -c "mv packaging/sources/*.gz packaging/"
    - bash -c "find packaging/*.gz -type f"
    fix-spec-file:
    - bash -c "sed -i -r \"0,/Release:/ s/Release:(\s*)\S*/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"
    post-upstream-clone:
    # builds from main branch should start with 100 release, to have high priority
    - bash -c "sed -i \"s/1%{?dist}/100%{?dist}/g\" packaging/leapp-repository.spec"


# NOTE: to see what envars, targets, .. can be set in tests, see
# the configuration of tests here:
#  7toX path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/rhel7/config.yaml
# >7tox path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/main/config.yaml
# Available only to RH Employees.

# ###################################################################### #
# ############################## 8 TO 9 ################################ #
# ###################################################################### #

# ###################################################################### #
# ### Abstract job definitions to make individual tests/jobs smaller ### #
# ###################################################################### #

#NOTE(pstodulk) putting default values in abstract jobs as from 8.10, as this
# is the last RHEL 8 release and all new future tests will start from this
# one release.

- &sanity-abstract-8to9
  job: tests
  trigger: ignore
  fmf_url: "https://gitlab.cee.redhat.com/oamg/leapp-tests"
  fmf_ref: "main"
  use_internal_tf: True
  labels:
    - sanity
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: sanity-abstract-8to9

- &sanity-abstract-8to9-aws
  <<: *sanity-abstract-8to9
  labels:
    - sanity
    - aws
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10-rhui]
  identifier: sanity-abstract-8to9-aws

- &beaker-minimal-8to9-abstract-ondemand
  <<: *sanity-abstract-8to9
  manual_trigger: True
  labels:
    - beaker-minimal
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: beaker-minimal-8to9-abstract-ondemand

- &kernel-rt-abstract-8to9-ondemand
  <<: *beaker-minimal-8to9-abstract-ondemand
  labels:
    - kernel-rt
  identifier: sanity-8to9-kernel-rt-abstract-ondemand

# ###################################################################### #
# ######################### Individual tests ########################### #
# ###################################################################### #

# Tests: 8.10 -> 9.4
- &sanity-810to94
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.4
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.4"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.4"

# On-demand minimal beaker tests
- &beaker-minimal-810to94
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.4"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.4"

# On-demand kernel-rt tests
- &kernel-rt-810to94
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.4"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.4"

# Tests: 8.10 -> 9.6
- &sanity-810to96
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.6
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.6"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.6"

# On-demand minimal beaker tests
- &beaker-minimal-810to96
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.6"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.6"

# On-demand kernel-rt tests
- &kernel-rt-810to96
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-8.10"
            distro_target: "rhel-9.6"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.6"

# ###################################################################### #
# ############################## 9 TO 10 ################################ #
# ###################################################################### #

# ###################################################################### #
# ### Abstract job definitions to make individual tests/jobs smaller ### #
# ###################################################################### #

- &sanity-abstract-9to10
  job: tests
  trigger: ignore
  fmf_url: "https://gitlab.cee.redhat.com/oamg/leapp-tests"
  fmf_ref: "main"
  use_internal_tf: True
  labels:
    - sanity
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6.0-Nightly]
  identifier: sanity-abstract-9to10

- &sanity-abstract-9to10-aws
  <<: *sanity-abstract-9to10
  labels:
    - sanity
    - aws
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6-rhui]
  identifier: sanity-abstract-9to10-aws

- &beaker-minimal-9to10-abstract-ondemand
  <<: *sanity-abstract-9to10
  manual_trigger: True
  labels:
    - beaker-minimal
  targets:
    epel-9-x86_64:
      distros: [RHEL-9.6.0-Nightly]
  identifier: beaker-minimal-9to10-abstract-ondemand

- &kernel-rt-abstract-9to10-ondemand
  <<: *beaker-minimal-9to10-abstract-ondemand
  labels:
    - kernel-rt
  identifier: sanity-9to10-kernel-rt-abstract-ondemand

# ###################################################################### #
# ######################### Individual tests ########################### #
# ###################################################################### #

# Tests: 9.6 -> 10.0
- &sanity-96to100
  <<: *sanity-abstract-9to10
  trigger: pull_request
  identifier: sanity-9.6to10.0
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:9to10 & tag:tier0 & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-9.6"
            distro_target: "rhel-10.0"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "9.6"
    TARGET_RELEASE: "10.0"

# On-demand minimal beaker tests
- &beaker-minimal-96to100
  <<: *beaker-minimal-9to10-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-9.6to10.0
    - 9.6to10.0
  identifier: sanity-9.6to10.0-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-9.6"
            distro_target: "rhel-10.0"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "9.6"
    TARGET_RELEASE: "10.0"

# On-demand kernel-rt tests
- &kernel-rt-96to100
  <<: *kernel-rt-abstract-9to10-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-9.6to10.0
    - 9.6to10.0
  identifier: sanity-9.6to10.0-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true'
    environments:
      - tmt:
          context:
            distro: "rhel-9.6"
            distro_target: "rhel-10.0"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    SOURCE_RELEASE: "9.6"
    TARGET_RELEASE: "10.0"
