FROM registry.centos.org/centos:8

VOLUME /payload

RUN dnf update -y && \
    dnf install python3-virtualenv python3-setuptools python3-pip make git -y

WORKDIR /payload
ENTRYPOINT make install-deps && make test
