"""
Top-level orchestration for the ``targetuserspacecreator`` actor (§4).

:func:`perform` is the actor's single entry point and the *only* producer of
messages. It runs the six observable steps in order and produces the three output
messages atomically, only after a successful build. Any hard-stop raised earlier
(input validation, missing cert, repo inhibitors, RHUI/dnf failures) means no
output messages.

High-layer module: imports every other ``tus_*`` module.
"""

from leapp import reporting
from leapp.libraries.actor import (
    tus_constants,
    tus_contentaccess,
    tus_inputdata,
    tus_layout,
    tus_targetrepos,
    tus_userspacebuild,
)
from leapp.libraries.common import rhsm
from leapp.libraries.common.config import get_product_type
from leapp.libraries.stdlib import api


def _report_missing_target_cert():
    """
    Inhibitor #1 - missing target product certificate (§8).

    Generated by translating the shared ``rhsm.MissingTargetProductCertificate``
    exception into a user-facing inhibitor. Includes a beta-specific note and the
    ``LEAPP_DEVEL_TARGET_RELEASE`` remediation, then soft-stops (no output).
    """
    summary = (
        'Cannot find a product certificate for the target system. This is'
        ' required to access the target content via subscription-manager.'
    )
    if get_product_type('target') == 'beta':
        summary += (
            ' Note that a Beta target requires a Beta product certificate; make'
            ' sure the target release you selected is available as Beta.'
        )
    reporting.create_report([
        reporting.Title('Missing target system product certificate'),
        reporting.Summary(summary),
        reporting.Severity(reporting.Severity.HIGH),
        reporting.Groups([reporting.Groups.SANITY]),
        reporting.Groups([reporting.Groups.INHIBITOR]),
        reporting.Remediation(hint=(
            'If the target version is not released yet, set the target release'
            ' explicitly via LEAPP_DEVEL_TARGET_RELEASE / --target-version.'
        )),
    ])


def perform():
    """Run the actor's six observable steps and produce the outputs (§4)."""
    # Step 1: consume + validate inputs (hard-stops #1-#3).
    inputs = tus_inputdata.gather()

    # Step 5 (paths): resolve the on-disk layout and overlay free-space reserve.
    layout = tus_layout.compute()

    try:
        # Step 2: establish the scratch container (overlay + nspawn + optional ISO).
        with tus_layout.scratch_container(layout, inputs) as scratch:
            # Step 3: establish content access (RHUI → RHSM → $stream → custom).
            tus_contentaccess.establish(scratch, inputs)

            # Step 4: discover + select target repositories (inhibitors #2-#5).
            used_repos = tus_targetrepos.select_target_repositories(scratch, inputs)

            # Step 5: build the target userspace.
            userspace_info = tus_userspacebuild.build(scratch, layout, inputs, used_repos)

            # Step 6: parse the build (scratch) container's repofiles for the snapshot.
            snapshot = tus_targetrepos.build_target_repositories_snapshot(scratch)
    except rhsm.MissingTargetProductCertificate:
        # Inhibitor #1: report + soft stop, no output messages.
        _report_missing_target_cert()
        return

    # Emit all three messages atomically, only on a successful build.
    api.produce(userspace_info, used_repos, snapshot)
