install-deps:
	# initscripts - /etc/sysconfig/network-scripts/ifcfg-* scripts
	# iproute - ip command
	# ethtool - ethtool command
	# systemd - journalctl command
	yum install -y initscripts iproute ethtool systemd
