FROM registry.access.redhat.com/ubi7/ubi:7.9

VOLUME /repo

RUN yum update -y && \
    yum install -y python-virtualenv python-setuptools make git rsync

# see ./Containerfile.ubi7 for explanation
RUN yum -y install python27-python-pip && \
    scl enable python27 -- pip install -U --target /usr/lib/python2.7/site-packages/ pip==20.3.0 && \
    python -m pip install --ignore-installed pip==20.3.4 ipaddress virtualenv

ENV PYTHON_VENV python2.7

COPY . /repocopy

WORKDIR /repocopy

RUN rm -rf tut*

RUN make clean && make install-deps

WORKDIR /

