FROM registry.access.redhat.com/ubi8/ubi:latest

VOLUME /repo

RUN dnf update -y && \
    dnf install -y python3-virtualenv python3-setuptools python3-pip make git rsync

ENV PYTHON_VENV python3.6

COPY . /repocopy

WORKDIR /repocopy

RUN rm -rf tut*

RUN make clean && make install-deps-fedora

WORKDIR /
