FROM fedora:42

VOLUME /repo

RUN dnf update -y && \
    dnf install -y findutils make rsync python3-gobject-base NetworkManager-libnm

ENV PYTHON_VENV python3.13

COPY . /repocopy

WORKDIR /repocopy

RUN rm -rf tut*

RUN make clean && make install-deps-fedora

WORKDIR /
