FROM centos:8

RUN sed -i s/mirror.centos.org/vault.centos.org/ /etc/yum.repos.d/CentOS-*.repo
RUN sed -i s/^#\s*baseurl=http/baseurl=http/ /etc/yum.repos.d/CentOS-*.repo
RUN sed -i s/^mirrorlist=http/#mirrorlist=http/ /etc/yum.repos.d/CentOS-*.repo

VOLUME /payload

RUN dnf update -y && \
    dnf install -y make git \
    python3-virtualenv python3-setuptools python3-pip \
    python3-gobject NetworkManager-libnm

WORKDIR /payload
ENTRYPOINT make install-deps && make test_no_lint
