FROM registry.access.redhat.com/ubi9/ubi:latest

VOLUME /payload

RUN dnf update -y && \
    dnf install python3-setuptools python3-pip make git -y

RUN pip install virtualenv

WORKDIR /payload
ENTRYPOINT make install-deps && make test_no_lint
