FROM registry.access.redhat.com/ubi8/ubi:latest

VOLUME /payload

RUN dnf update -y && \
    dnf install python3-virtualenv python3-setuptools python3-pip make git -y

WORKDIR /payload
ENTRYPOINT make install-deps && make lint
