# IMPORTANT NOTE
# In this workflow there should NOT be checkout action - because of security reasons.
# More info:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: PR welcome message
on:
  pull_request_target:
    types: opened

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## **Thank you for contributing to the Leapp project!**
            Please note that every PR needs to comply with the [Leapp Guidelines](https://leapp.readthedocs.io/en/latest/contributing.html#) and must pass all tests in order to be mergeable.
            If you want to request a review or rebuild a package in copr, you can use following commands as a comment:
            - **review please @oamg/developers** to notify leapp developers of the review request
            - **/packit copr-build** to submit a public copr build using packit

            Packit will automatically schedule regression tests for this PR's build and latest upstream leapp build. If you need a different version of leapp, e.g. from PR#42, use `/packit test oamg/leapp#42`
            Note that first time contributors cannot run tests automatically - they will be started by a reviewer.

            It is possible to schedule specific on-demand tests as well. Currently 2 test sets are supported, `beaker-minimal` and `kernel-rt`, both can be used to be run on all upgrade paths or just a couple of specific ones.
            To launch on-demand tests with packit:
            - **/packit test --labels kernel-rt** to schedule `kernel-rt` tests set for all upgrade paths
            - **/packit test --labels beaker-minimal-8.10to9.4,kernel-rt-8.10to9.4** to schedule `kernel-rt` and `beaker-minimal` test sets for 8.10->9.4 upgrade path

            See other labels for particular jobs defined in the `.packit.yaml` file.

            Please [open ticket](https://url.corp.redhat.com/oamg-ci-issue) in case you experience technical problem with the CI. (RH internal only)

            **Note:** In case there are problems with tests not being triggered automatically on new PR/commit or pending for a long time, please contact leapp-infra.
